"""ajout table parametres

Revision ID: 20b2cd0f7293
Revises: 158e166a3684
Create Date: 2026-07-24 13:17:35.999981

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '20b2cd0f7293'
down_revision = '158e166a3684'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('parametres',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nom_entreprise', sa.String(length=150), nullable=True),
    sa.Column('identifiant_fiscal', sa.String(length=50), nullable=True),
    sa.Column('adresse', sa.String(length=255), nullable=True),
    sa.Column('telephone', sa.String(length=30), nullable=True),
    sa.Column('email', sa.String(length=150), nullable=True),
    sa.Column('taux_tva', sa.Float(), nullable=True),
    sa.Column('logo', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('produits', schema=None) as batch_op:
        batch_op.alter_column('description',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.Text(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('produits', schema=None) as batch_op:
        batch_op.alter_column('description',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)

    op.drop_table('parametres')
    # ### end Alembic commands ###
