"""mot de passe client pour le portail

Revision ID: 30f17fe645f8
Revises: 63e833c6f00a
Create Date: 2026-07-27 01:18:44.904931

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '30f17fe645f8'
down_revision = '63e833c6f00a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clients', schema=None) as batch_op:
        batch_op.add_column(sa.Column('mot_de_passe_hash', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clients', schema=None) as batch_op:
        batch_op.drop_column('mot_de_passe_hash')

    # ### end Alembic commands ###
