"""Creation de la table utilisateurs

Revision ID: 361bbc83aa57
Revises: 
Create Date: 2026-07-15 16:40:32.613963

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '361bbc83aa57'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('utilisateurs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nom', sa.String(length=100), nullable=False),
    sa.Column('prenom', sa.String(length=100), nullable=False),
    sa.Column('telephone', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=150), nullable=False),
    sa.Column('mot_de_passe_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=30), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('utilisateurs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_utilisateurs_email'), ['email'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('utilisateurs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_utilisateurs_email'))

    op.drop_table('utilisateurs')
    # ### end Alembic commands ###
