"""mode de paiement prevu sur facture

Revision ID: 3be55efb9128
Revises: 8902773d1a06
Create Date: 2026-07-30 17:27:05.336613

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3be55efb9128'
down_revision = '8902773d1a06'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('factures', schema=None) as batch_op:
        batch_op.add_column(sa.Column('mode_paiement_prevu', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('factures', schema=None) as batch_op:
        batch_op.drop_column('mode_paiement_prevu')

    # ### end Alembic commands ###
