"""categorie produit, envoyee facture, objectif ca mensuel

Revision ID: 63e833c6f00a
Revises: 9920f9f65b8e
Create Date: 2026-07-26 18:03:13.872104

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '63e833c6f00a'
down_revision = '9920f9f65b8e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('factures', schema=None) as batch_op:
        batch_op.add_column(sa.Column('envoyee', sa.Boolean(), nullable=False, server_default=sa.false()))
        batch_op.add_column(sa.Column('date_envoi', sa.DateTime(), nullable=True))

    with op.batch_alter_table('parametres', schema=None) as batch_op:
        batch_op.add_column(sa.Column('objectif_ca_mensuel', sa.Numeric(precision=10, scale=2), nullable=True))

    with op.batch_alter_table('produits', schema=None) as batch_op:
        batch_op.add_column(sa.Column('categorie', sa.String(length=80), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('produits', schema=None) as batch_op:
        batch_op.drop_column('categorie')

    with op.batch_alter_table('parametres', schema=None) as batch_op:
        batch_op.drop_column('objectif_ca_mensuel')

    with op.batch_alter_table('factures', schema=None) as batch_op:
        batch_op.drop_column('date_envoi')
        batch_op.drop_column('envoyee')

    # ### end Alembic commands ###
