"""numeric prix total et cascade details facture

Revision ID: 9920f9f65b8e
Revises: 20b2cd0f7293
Create Date: 2026-07-26 17:06:42.942606

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9920f9f65b8e'
down_revision = '20b2cd0f7293'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('details_facture', schema=None) as batch_op:
        batch_op.alter_column('prix_unitaire',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=10, scale=2),
               existing_nullable=False)

    with op.batch_alter_table('factures', schema=None) as batch_op:
        batch_op.alter_column('total',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=10, scale=2),
               existing_nullable=True)

    with op.batch_alter_table('produits', schema=None) as batch_op:
        batch_op.alter_column('prix',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=10, scale=2),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('produits', schema=None) as batch_op:
        batch_op.alter_column('prix',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=sa.FLOAT(),
               existing_nullable=False)

    with op.batch_alter_table('factures', schema=None) as batch_op:
        batch_op.alter_column('total',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=sa.FLOAT(),
               existing_nullable=True)

    with op.batch_alter_table('details_facture', schema=None) as batch_op:
        batch_op.alter_column('prix_unitaire',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=sa.FLOAT(),
               existing_nullable=False)

    # ### end Alembic commands ###
