"""ajout horaires ouverture parametres

Revision ID: fe04ac553412
Revises: 3be55efb9128
Create Date: 2026-08-11 12:16:40.993618

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fe04ac553412'
down_revision = '3be55efb9128'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('parametres', schema=None) as batch_op:
        batch_op.add_column(sa.Column('horaires_ouverture', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('parametres', schema=None) as batch_op:
        batch_op.drop_column('horaires_ouverture')

    # ### end Alembic commands ###
